
package Vista;

import Control.Control;

public class AgregarCaballo extends javax.swing.JFrame {

    private Control control;

    /**
     * Creates new form Nombres
     */
    public AgregarCaballo(Control aThis) {
        initComponents();
        setLocationRelativeTo(null);
        control = aThis;
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNombreAgregar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 186, 106));
        jPanel1.setForeground(new java.awt.Color(51, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Agregar Caballo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 30, 250, 29);

        textNombreAgregar.setBackground(new java.awt.Color(255, 217, 174));
        textNombreAgregar.setBorder(null);
        textNombreAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(textNombreAgregar);
        textNombreAgregar.setBounds(30, 120, 280, 30);

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ingrese el nombre del caballo a agregar:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 90, 310, 20);

        botonAgregar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(51, 51, 51));
        botonAgregar.setText("Agregar");
        botonAgregar.setBorder(null);
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(botonAgregar);
        botonAgregar.setBounds(150, 180, 140, 30);

        botonSalir.setBackground(new java.awt.Color(255, 186, 106));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/salir.png"))); // NOI18N
        botonSalir.setBorder(null);
        jPanel1.add(botonSalir);
        botonSalir.setBounds(410, 20, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Caballo128.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 50, 120, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void textNombreAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreAgregarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAgregar;
    public javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField textNombreAgregar;
    // End of variables declaration//GEN-END:variables
}
