package Vista;

import Control.Control;

public class Carrera extends javax.swing.JFrame {

    private Control control;

    /**
     * Creates new form Carrera
     */
    public Carrera(Control aThis) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Caballo2 = new javax.swing.JLabel();
        Caballo1 = new javax.swing.JLabel();
        Caballo3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonInterrumpir = new javax.swing.JToggleButton();
        botonTerminar = new javax.swing.JToggleButton();
        botonEmpezar1 = new javax.swing.JToggleButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 186, 106));
        jPanel1.setForeground(new java.awt.Color(51, 204, 0));
        jPanel1.setLayout(null);

        Titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(204, 0, 0));
        Titulo.setText("Carrera de Caballos");
        jPanel1.add(Titulo);
        Titulo.setBounds(240, 30, 310, 29);

        botonSalir.setBackground(new java.awt.Color(255, 186, 106));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/salir.png"))); // NOI18N
        botonSalir.setBorder(null);
        jPanel1.add(botonSalir);
        botonSalir.setBounds(670, 30, 30, 30);

        jPanel2.setBackground(new java.awt.Color(252, 251, 249));
        jPanel2.setLayout(null);

        Caballo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/animal-3629_128.gif"))); // NOI18N
        jPanel2.add(Caballo2);
        Caballo2.setBounds(420, 90, 93, 50);

        Caballo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/animal-3629_128.gif"))); // NOI18N
        jPanel2.add(Caballo1);
        Caballo1.setBounds(420, 10, 93, 50);

        Caballo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/animal-3629_128.gif"))); // NOI18N
        jPanel2.add(Caballo3);
        Caballo3.setBounds(420, 170, 93, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Meta.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 0, 40, 220);

        jLabel2.setText("________________________________________________________________________________________");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 140, 460, 16);

        jLabel4.setText("________________________________________________________________________________________");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 60, 460, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("3");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(520, 160, 40, 60);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("1");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(520, 10, 40, 60);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("2");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(520, 90, 40, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 80, 550, 220);

        botonInterrumpir.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        botonInterrumpir.setForeground(new java.awt.Color(51, 51, 51));
        botonInterrumpir.setText("Interrumpir");
        botonInterrumpir.setBorder(null);
        botonInterrumpir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInterrumpirActionPerformed(evt);
            }
        });
        jPanel1.add(botonInterrumpir);
        botonInterrumpir.setBounds(350, 330, 150, 23);

        botonTerminar.setBackground(new java.awt.Color(253, 231, 231));
        botonTerminar.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        botonTerminar.setForeground(new java.awt.Color(51, 51, 51));
        botonTerminar.setText("Terminar Carrera");
        botonTerminar.setBorder(null);
        botonTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonTerminar);
        botonTerminar.setBounds(530, 330, 150, 23);

        botonEmpezar1.setBackground(new java.awt.Color(225, 255, 214));
        botonEmpezar1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        botonEmpezar1.setForeground(new java.awt.Color(51, 51, 51));
        botonEmpezar1.setText("Empezar Carrera");
        botonEmpezar1.setBorder(null);
        jPanel1.add(botonEmpezar1);
        botonEmpezar1.setBounds(160, 330, 150, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInterrumpirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInterrumpirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInterrumpirActionPerformed

    private void botonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTerminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caballo1;
    private javax.swing.JLabel Caballo2;
    private javax.swing.JLabel Caballo3;
    private javax.swing.JLabel Titulo;
    private javax.swing.JToggleButton botonEmpezar1;
    private javax.swing.JToggleButton botonInterrumpir;
    private javax.swing.JButton botonSalir;
    private javax.swing.JToggleButton botonTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
